name: Deploy Website

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Allow writing to repo
      pages: write     # Allow GitHub Pages deployment
      id-token: write  # Required for authentication

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./templates  # Deploy from templates/
